package:
  name: ruamel
  version: 0.16.12

source:
  sha256: 076cc0bc34f1966d920a49f18b52b6ad559fbe656a0748e3535cf7b3f29ebf9e
  url: https://files.pythonhosted.org/packages/17/2f/f38332bf6ba751d1c8124ea70681d2b2326d69126d9058fbd9b4c434d268/ruamel.yaml-0.16.12.tar.gz
  patches:
    - patches/remove_pip_install_check.patch

requirements:
  run:
    - setuptools

test:
  imports:
    - ruamel.yaml
