package:
  name: ruamel
  version: 0.16.10

source:
  sha256: 099c644a778bf72ffa00524f78dd0b6476bca94a1da344130f4bf3381ce5b954
  url: https://files.pythonhosted.org/packages/16/8b/54a26c1031595e5edd0e616028b922d78d8ffba8bc775f0a4faeada846cc/ruamel.yaml-0.16.10.tar.gz
  patches:
    - patches/remove_pip_install_check.patch

requirements:
  run:
    - setuptools

test:
  imports:
  - ruamel.yaml
